"use client";
import {FormEvent,useState} from "react";
export default function Track(){
 const [orderNumber,setOrderNumber]=useState(""); const [email,setEmail]=useState(""); const [order,setOrder]=useState<any>(null); const [selected,setSelected]=useState<string|null>(null); const [note,setNote]=useState(""); const [msg,setMsg]=useState("");
 async function lookup(e:FormEvent){e.preventDefault();setMsg("");const r=await fetch("/api/customer/lookup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderNumber,email})});const b=await r.json();if(!r.ok){setMsg(b.error||"Order not found");return;}setOrder(b.order);setSelected(b.order.previews.at(-1)?.id||null)}
 async function approve(){const r=await fetch("/api/customer/approve",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderNumber,email,previewId:selected})});const b=await r.json();setMsg(r.ok?"Design approved.":b.error)}
 async function revision(){const r=await fetch("/api/customer/revision",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderNumber,email,previewId:selected,message:note})});const b=await r.json();setMsg(r.ok?"Revision request sent.":b.error)}
 if(!order)return <main className="container"><section className="hero"><h1>Track My Order</h1></section><form className="card grid" onSubmit={lookup}><input placeholder="#1048" value={orderNumber} onChange={e=>setOrderNumber(e.target.value)} required/><input type="email" placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)} required/><button className="btn primary">View Artwork</button>{msg&&<p>{msg}</p>}</form></main>;
 const p=order.previews.find((x:any)=>x.id===selected)||order.previews.at(-1);
 return <main className="container" style={{padding:"40px 0"}}><h1>Order #{order.order_number}</h1><p>{msg}</p><div className="layout"><section className="card">{p?.imageUrl?<img className="preview" src={p.imageUrl}/>:<p>Preview is not ready yet.</p>}<div className="thumbs">{order.previews.map((x:any)=><button className="thumb" key={x.id} onClick={()=>setSelected(x.id)}>{x.imageUrl&&<img className="preview" src={x.imageUrl}/>}<small>{x.label}</small></button>)}</div></section><aside className="card grid"><p>Free revisions remaining: {order.remainingFreeRevisions}</p><button className="btn gold" onClick={approve}>Approve selected design</button><textarea placeholder="Describe the changes" value={note} onChange={e=>setNote(e.target.value)}/><button className="btn primary" onClick={revision}>Request revision</button></aside></div></main>}
