"use client";
import { useCallback, useEffect, useState } from "react";

type OrderSummary = { id: string; order_number: string; customer_name: string; customer_email: string; status: string; revision_count: number; updated_at: string };

export default function Admin() {
  const [key, setKey] = useState(""); const [loggedIn, setLoggedIn] = useState(false); const [orders, setOrders] = useState<OrderSummary[]>([]);
  const [selected, setSelected] = useState<any>(null); const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [filter, setFilter] = useState("all"); const [search, setSearch] = useState("");

  const load = useCallback(async () => { setBusy(true); const response = await fetch(`/api/admin/orders?status=${filter}`); const body = await response.json(); setBusy(false); if (response.ok) { setLoggedIn(true); setOrders(body.orders); } else { setLoggedIn(false); if (response.status !== 401) setMessage(body.error); } }, [filter]);
  useEffect(() => { void load(); }, [load]);
  async function login() { setBusy(true); const response = await fetch("/api/admin/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ key }) }); const body = await response.json(); setBusy(false); if (!response.ok) return setMessage(body.error); setKey(""); setLoggedIn(true); await load(); }
  async function detail(id: string) { const response = await fetch(`/api/admin/orders/${id}`); const body = await response.json(); if (response.ok) setSelected(body.order); else setMessage(body.error); }
  async function upload() { if (!selected || !file) return; setBusy(true); const form = new FormData(); form.append("orderId", selected.id); form.append("file", file); const response = await fetch("/api/admin/upload-preview", { method: "POST", body: form }); const body = await response.json(); setBusy(false); setMessage(response.ok ? (body.emailSent ? "Preview uploaded and customer notified." : "Preview uploaded. Email delivery was not confirmed.") : body.error); if (response.ok) { setFile(null); await detail(selected.id); await load(); } }
  async function action(action: string, revisionId?: string) { setBusy(true); const response = await fetch(`/api/admin/orders/${selected.id}/status`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, revisionId }) }); const body = await response.json(); setBusy(false); setMessage(response.ok ? "Order updated." : body.error); if (response.ok) { await detail(selected.id); await load(); } }
  async function logout() { await fetch("/api/admin/logout", { method: "POST" }); setLoggedIn(false); setSelected(null); setOrders([]); }

  if (!loggedIn) return <main className="container page-space"><section className="hero compact"><span className="eyebrow">SECURE AREA</span><h1>Pawtra Admin</h1></section><div className="card login-card grid"><label>Admin key<input type="password" value={key} onChange={(e) => setKey(e.target.value)} onKeyDown={(e) => e.key === "Enter" && login()} /></label><button className="btn primary" disabled={busy} onClick={login}>{busy ? "Opening…" : "Open dashboard"}</button>{message && <p className="notice error">{message}</p>}</div></main>;

  return <main className="container page-space admin-page"><div className="topline"><div><span className="eyebrow">ORDER MANAGEMENT</span><h1>Pawtra Admin</h1></div><button className="btn secondary" onClick={logout}>Log out</button></div>{message && <p className="notice success">{message}</p>}
    <div className="admin-grid"><section><div className="toolbar"><select aria-label="Filter orders by status" value={filter} onChange={(e) => setFilter(e.target.value)}><option value="all">All orders</option><option value="artwork_in_progress">Artwork in progress</option><option value="revision_requested">Revision requested</option><option value="preview_ready">Preview ready</option><option value="approved">Approved</option><option value="in_production">In production</option><option value="shipped">Shipped</option></select><span>{orders.length} orders</span></div><input aria-label="Search orders" placeholder="Search order, customer, or email" value={search} onChange={(e) => setSearch(e.target.value)} /><div className="order-list">{orders.filter((order) => `${order.order_number} ${order.customer_name || ""} ${order.customer_email}`.toLowerCase().includes(search.trim().toLowerCase())).map((order) => <button className={`order-row ${selected?.id === order.id ? "active" : ""}`} key={order.id} onClick={() => detail(order.id)}><div><strong>#{order.order_number}</strong><span>{order.customer_name || order.customer_email}</span></div><div><span className={`badge ${order.status}`}>{order.status.replaceAll("_", " ")}</span><small>{order.revision_count}/3 revisions</small></div></button>)}</div>{!busy && orders.length === 0 && <p className="muted">No orders match this filter.</p>}</section>
      <section>{selected ? <div className="card detail-card"><div className="detail-head"><div><span className="eyebrow">ORDER #{selected.order_number}</span><h2>{selected.customer_name || selected.customer_email}</h2><p className="muted">{selected.customer_email}</p></div><span className={`badge ${selected.status}`}>{selected.status.replaceAll("_", " ")}</span></div>
        {selected.previews?.length > 0 && <div className="admin-previews">{selected.previews.map((p: any) => <figure key={p.id}><img src={p.imageUrl} alt={p.label} /><figcaption>{p.label}</figcaption></figure>)}</div>}
        {(["artwork_in_progress", "revision_requested"].includes(selected.status)) && <div className="section-block"><h3>{selected.status === "revision_requested" ? "Upload revised preview" : "Upload initial preview"}</h3><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => setFile(e.target.files?.[0] || null)} /><button className="btn primary" disabled={!file || busy || Boolean(selected.approved_at)} onClick={upload}>Upload preview</button><p className="muted small">JPEG, PNG, or WebP; maximum 12 MB. A revised upload completes the latest open request.</p></div>}
        <div className="section-block"><h3>Revision requests</h3>{selected.revisionRequests?.length ? selected.revisionRequests.map((r: any) => <div className="revision-card" key={r.id}><div><strong>{r.status === "open" ? "Open" : "Completed"}</strong><p>{r.message}</p><small className="muted">{new Date(r.created_at).toLocaleString()}{r.completed_at ? ` · completed ${new Date(r.completed_at).toLocaleString()}` : ""}</small></div></div>) : <p className="muted">No revision requests.</p>}</div>
        {(selected.status === "approved" || selected.status === "in_production") && <div className="section-block"><h3>Order actions</h3><div className="button-row">{selected.status === "approved" && <button disabled={busy} className="btn gold" onClick={() => action("mark_production")}>Move to production</button>}{selected.status === "in_production" && <button disabled={busy} className="btn primary" onClick={() => action("mark_shipped")}>Mark shipped</button>}</div></div>}
        <div className="section-block"><h3>Activity</h3>{selected.auditEvents?.length ? selected.auditEvents.map((event: any) => <div className="history" key={event.id}><strong>{event.event_type.replaceAll("_", " ")}</strong><p className="muted small">{new Date(event.created_at).toLocaleString()}</p></div>) : <p className="muted">No activity recorded.</p>}</div>
      </div> : <div className="card empty-state"><h2>Select an order</h2><p>Order details will appear here.</p></div>}</section></div>
  </main>;
}
