"use client";
import { useEffect, useState } from "react";

type OrderSummary = { id: string; order_number: string; customer_name: string; customer_email: string; status: string; revision_count: number; updated_at: string };

export default function Admin() {
  const [key, setKey] = useState(""); const [loggedIn, setLoggedIn] = useState(false); const [orders, setOrders] = useState<OrderSummary[]>([]);
  const [selected, setSelected] = useState<any>(null); const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [filter, setFilter] = useState("all");

  async function load() { setBusy(true); const response = await fetch(`/api/admin/orders?status=${filter}`); const body = await response.json(); setBusy(false); if (response.ok) { setLoggedIn(true); setOrders(body.orders); } else { setLoggedIn(false); if (response.status !== 401) setMessage(body.error); } }
  useEffect(() => { load(); }, [filter]);
  async function login() { setBusy(true); const response = await fetch("/api/admin/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ key }) }); const body = await response.json(); setBusy(false); if (!response.ok) return setMessage(body.error); setKey(""); setLoggedIn(true); await load(); }
  async function detail(id: string) { const response = await fetch(`/api/admin/orders/${id}`); const body = await response.json(); if (response.ok) setSelected(body.order); else setMessage(body.error); }
  async function upload() { if (!selected || !file) return; setBusy(true); const form = new FormData(); form.append("orderId", selected.id); form.append("file", file); const response = await fetch("/api/admin/upload-preview", { method: "POST", body: form }); const body = await response.json(); setBusy(false); setMessage(response.ok ? "Preview uploaded and customer notified." : body.error); if (response.ok) { setFile(null); await detail(selected.id); await load(); } }
  async function action(action: string, revisionId?: string) { setBusy(true); const response = await fetch(`/api/admin/orders/${selected.id}/status`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, revisionId }) }); const body = await response.json(); setBusy(false); setMessage(response.ok ? "Order updated." : body.error); if (response.ok) { await detail(selected.id); await load(); } }
  async function logout() { await fetch("/api/admin/logout", { method: "POST" }); setLoggedIn(false); setSelected(null); setOrders([]); }

  if (!loggedIn) return <main className="container page-space"><section className="hero compact"><span className="eyebrow">SECURE AREA</span><h1>Pawtra Admin</h1></section><div className="card login-card grid"><label>Admin key<input type="password" value={key} onChange={(e) => setKey(e.target.value)} onKeyDown={(e) => e.key === "Enter" && login()} /></label><button className="btn primary" disabled={busy} onClick={login}>{busy ? "Opening…" : "Open dashboard"}</button>{message && <p className="notice error">{message}</p>}</div></main>;

  return <main className="container page-space admin-page"><div className="topline"><div><span className="eyebrow">ORDER MANAGEMENT</span><h1>Pawtra Admin</h1></div><button className="btn secondary" onClick={logout}>Log out</button></div>{message && <p className="notice success">{message}</p>}
    <div className="admin-grid"><section><div className="toolbar"><select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="all">All orders</option><option value="revision_requested">Revision requested</option><option value="preview_ready">Preview ready</option><option value="approved">Approved</option><option value="in_production">In production</option></select><span>{orders.length} orders</span></div><div className="order-list">{orders.map((order) => <button className={`order-row ${selected?.id === order.id ? "active" : ""}`} key={order.id} onClick={() => detail(order.id)}><div><strong>#{order.order_number}</strong><span>{order.customer_name || order.customer_email}</span></div><div><span className={`badge ${order.status}`}>{order.status.replaceAll("_", " ")}</span><small>{order.revision_count}/3 revisions</small></div></button>)}</div></section>
      <section>{selected ? <div className="card detail-card"><div className="detail-head"><div><span className="eyebrow">ORDER #{selected.order_number}</span><h2>{selected.customer_name || selected.customer_email}</h2><p className="muted">{selected.customer_email}</p></div><span className={`badge ${selected.status}`}>{selected.status.replaceAll("_", " ")}</span></div>
        {selected.previews?.length > 0 && <div className="admin-previews">{selected.previews.map((p: any) => <figure key={p.id}><img src={p.imageUrl} alt={p.label} /><figcaption>{p.label}</figcaption></figure>)}</div>}
        <div className="section-block"><h3>Upload next preview</h3><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => setFile(e.target.files?.[0] || null)} /><button className="btn primary" disabled={!file || busy || Boolean(selected.approved_at)} onClick={upload}>Upload and notify customer</button></div>
        <div className="section-block"><h3>Revision requests</h3>{selected.revisionRequests?.length ? selected.revisionRequests.map((r: any) => <div className="revision-card" key={r.id}><div><strong>{r.status === "open" ? "Open" : "Completed"}</strong><p>{r.message}</p></div>{r.status === "open" && <button className="btn secondary" disabled={busy} onClick={() => action("complete_revision", r.id)}>Mark completed</button>}</div>) : <p className="muted">No revision requests.</p>}</div>
        <div className="section-block"><h3>Order actions</h3><div className="button-row"><button className="btn secondary" onClick={() => action("mark_in_progress")}>Artwork in progress</button><button className="btn gold" onClick={() => action("mark_production")}>Move to production</button><button className="btn primary" onClick={() => action("mark_shipped")}>Mark shipped</button></div></div>
      </div> : <div className="card empty-state"><h2>Select an order</h2><p>Order details will appear here.</p></div>}</section></div>
  </main>;
}
